### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by 224XS** [12q/Up2Dater#1]
Great idea, but the sample as provided fails.
Called versionManager.checkNewVersionAfter { [weak self] result in....   from viewDidAppear
   nothing happen -> tracing reveals that inside. AppStoreVersionManager.checkNewVersionAfter...
       that inside the switch on localBundleInfo.sucess that self? is nil, so loadRequest does not fire

Then I tried calling this func from inside viewDidAppear:

```
    func checkNewVersion() {
        let versionManager = AppStoreVersionManager()
        versionManager.checkNewVersion(with: { result in
            print(result)
            switch result{
            case .success(let version):
                print("version: \(version.debugDescription)")
                guard let version = version else {return}
                self.presentUpdateAlert(for: version)
            case .failure(let error):
                print("error: \(error.description)")
            }
            print("done with versionCheck")
        })
        print("done with call to checkNewVersion")

and none of the prints inside the completion closure fire.

Any ideas?

**Comment by 12q** [comment]
> Great idea, but the sample as provided fails. Called versionManager.checkNewVersionAfter { [weak self] result in.... from viewDidAppear nothing happen -> tracing reveals that inside. AppStoreVersionManager.checkNewVersionAfter... that inside the switch on localBundleInfo.sucess that self? is nil, so loadRequest does not fire
> 
> Then I tried calling this func from inside viewDidAppear:
> 
> ```
>     func checkNewVersion() {
>         let versionManager = AppStoreVersionManager()
>         versionManager.checkNewVersion(with: { result in
>             print(result)
>             switch result{
>             case .success(let version):
>                 print("version: \(version.debugDescription)")
>                 guard let version = version else {return}
>                 self.presentUpdateAlert(for: version)
>             case .failure(let error):
>                 print("error: \(error.description)")
>             }
>             print("done with versionCheck")
>         })
>         print("done with call to checkNewVersion")
> 
> and none of the prints inside the completion closure fire.
> 
> Any ideas?
> ```

Thanks for pointing out!
Hello, it seems that the instance of the `AppStoreVersionManager` has been deallocated before the the completion `versionManager.checkNewVersionAfter ` is called.
That's why we need to declare `let versionManager = AppStoreVersionManager()` outside the function scope as a property.
Please, give it a try

```swift
import Up2Dater
    let versionManager = AppStoreVersionManager()

    func checkNewVersion() {
        versionManager.checkNewVersionAfter { [weak self] result in
            switch result {
                case .success(let version):
                    guard let version = version else { return }
                    self?.presentUpdateAlert(for: version)
                case .failure(let error):
                    print(error.description)
            }
        }
    }
```
