### ISSUE TITLE
Version detected  by Up2Dater is not the latest

### ISSUE THREAD

**Issue by SimonKravis** [12q/Up2Dater#2]
I have an iOS App store app which was updated 9 hrs ago from v 2.2  to v 2.3 but Up2Dater Cocoa Pod in the Swift source code (running in XCode 14) returns v 2.2 as the latest version. App store path is itms-app://apple.com/app/id1626408234. If I load this URL into Safari I see version 2.3. Restarting the device doesn't fix the problem.

**Comment by 12q** [comment]
Hello, I'll check it out. Thanks @SimonKravis

**Comment by 12q** [comment]
@SimonKravis
Can't reproduce this issue on xCode (Version 13.4.1 (13F100)).
¯\_(ツ)_/¯ 
I simulate test for case with local version and  `v2.2` and your BundleId, and it was successful (it returns `v2.3`). 

You might install this Pod as a Development pod (pod 'Up2Dater', :path => '~/...your-path.../Up2Dater')
and place breakpoint in [func isNewer(then bundleVersion: String) -> Bool]   (https://github.com/12q/Up2Dater/blob/828262ab0ea61f24db6d5e0036ec3335c2811426/Up2Dater/Classes/AppStoreVersion.swift#L33-L42)
Ping me up if you find something. 
Btw, is your Identity section for the Target filled properly?
<img width="574" alt="Screenshot 2022-11-01 at 14 56 27" src="https://user-images.githubusercontent.com/740879/199237656-06c0c360-c381-484e-ae4d-607faa0e1075.png">

**Comment by SimonKravis** [comment]
A few comments about similar problems mention that Apple have a lot of App Store servers and it may take time for updates to propagate but same problem today (from Australia), and it's now over 24 hrs since new version available. Will keep trying. The fact that Safari shows the update OK is puzzling. Looks as though Up2Dater may be using cached URL content, but I doubt if you'd bother to do that.

**Comment by SimonKravis** [comment]
When I change the region to United States and restart it works OK! Not your fault.

**Comment by SimonKravis** [comment]
Changing region on iOS device back to Australia it now works OK.

**Comment by SimonKravis** [comment]
Thanks for a very useful Pod.

**Comment by SimonKravis** [comment]
Might be worth advising non-US users to change region to US and back again - Up2Dater works OK after this without a restart

**Comment by 12q** [comment]
@SimonKravis glad to hear that!

here's the command that I use for version checkin, but It's seems to be kinda global URL 
and it might be the different results for locations (and that's weird).
`curl http://itunes.apple.com/lookup\?bundleId\=com.AlekaConsulting.XXX_xx_Xx`

We might check the URL responses for different locations by using VPN.

Not, I'm not caching
```
                    let request = URLRequest(
                        url: appStoreURL,
                        cachePolicy: .reloadIgnoringLocalCacheData
                    )
```

**Comment by SimonKravis** [comment]
Tried to reproduce the problem with a fresh OS on iPad and couldn't so perhaps it is delay in updating all the App Store servers around the world. I'll check next time I do an app update, but it seems unlikely that it would take > 24 hrs to update all the App Store servers.

**Comment by 12q** [comment]
I guess you right. Anyway thank you for pointed out on that case.
